### ISSUE TITLE
Cannot install on React ^18.2.0

### ISSUE THREAD

**Issue by Agilulfo1820** [emilkowalski/sonner#515]
`yarn add sonner` returns a 
```
error Invariant Violation: expected workspace package to exist for "resolve"
    at invariant (/Users/danrusnac/.cache/node/corepack/yarn/1.22.22/lib/cli.js:2318:15)
    at _loop2 (/Users/danrusnac/.cache/node/corepack/yarn/1.22.22/lib/cli.js:91560:9)
    at PackageHoister.init (/Users/danrusnac/.cache/node/corepack/yarn/1.22.22/lib/cli.js:91619:19)
    at PackageLinker.getFlatHoistedTree (/Users/danrusnac/.cache/node/corepack/yarn/1.22.22/lib/cli.js:48551:20)
    at PackageLinker.<anonymous> (/Users/danrusnac/.cache/node/corepack/yarn/1.22.22/lib/cli.js:48562:27)
    at Generator.next (<anonymous>)
    at step (/Users/danrusnac/.cache/node/corepack/yarn/1.22.22/lib/cli.js:310:30)
    at /Users/danrusnac/.cache/node/corepack/yarn/1.22.22/lib/cli.js:328:14
    at new Promise (<anonymous>)
    at new F (/Users/danrusnac/.cache/node/corepack/yarn/1.22.22/lib/cli.js:5539:28)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by emilkowalski** [comment]
Fixed in #493
